name: C++ CI with Automake

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool

      - name: Generate build system
        run: |
          aclocal
          autoconf
          automake --add-missing

      - name: Build
        run: |
          ./configure
          make

      - name: Create tarball
        run: |
          make dist
